// ─── Chilean communes — shared across all address inputs ────────────────────
export const COMUNAS = [
  "Alhué","Alto Biobío","Alto del Carmen","Alto Hospicio","Ancud","Andacollo","Angol",
  "Antofagasta","Arauco","Arica","Aysén","Buin","Bulnes","Cabildo","Cabo de Hornos",
  "Calama","Caldera","Calera","Calera de Tango","Camarones","Carahue","Cartagena",
  "Castro","Cauquenes","Chaitén","Chañaral","Chimbarongo","Chiguayante","Chillán",
  "Chillán Viejo","Chonchi","Cisnes","Colchane","Colina","Coltauco","Combarbalá",
  "Concepción","Conchalí","Concón","Constitución","Copiapó","Coquimbo","Coronel",
  "Corral","Coyhaique","Curicó","Dalcahue","El Bosque","El Monte","El Quisco",
  "El Tabo","Estación Central","Freire","Freirina","Fresia","Frutillar","Futrono",
  "General Lagos","Graneros","Gorbea","Hijuelas","Hualaihué","Hualqui","Huara",
  "Huasco","Huechuraba","Illapel","Independencia","Isla de Maipo","Iquique",
  "La Calera","La Cisterna","La Cruz","La Florida","La Granja","La Ligua",
  "La Pintana","La Reina","La Serena","La Unión","Lago Ranco","Lampa","Lanco",
  "Las Cabras","Las Condes","Lautaro","Lebu","Limache","Linares","Lo Barnechea",
  "Lo Espejo","Lo Prado","Longaví","Los Álamos","Los Andes","Los Lagos",
  "Los Muermos","Los Vilos","Los Ángeles","Lota","Macul","Maipú","Máfil",
  "María Elena","María Pinto","Mariquina","Maullín","Mejillones","Melipilla",
  "Molina","Monte Patria","Mostazal","Mulchén","Nacimiento","Nueva Imperial",
  "Ñuñoa","Nogales","Ollagüe","Olmué","Osorno","Ovalle","Padre Hurtado",
  "Padre Las Casas","Paillaco","Paine","Panguipulli","Papudo","Parral",
  "Pedro Aguirre Cerda","Peñaflor","Peñalolén","Penco","Petorca","Peumo",
  "Pica","Pichidegua","Pichilemu","Pitrufquén","Pirque","Porvenir",
  "Pozo Almonte","Providencia","Puchuncaví","Pudahuel","Puerto Montt",
  "Puerto Natales","Puerto Varas","Puerto Williams","Puente Alto","Punitaqui",
  "Purranque","Punta Arenas","Pucón","Putre","Quellón","Quilicura","Quilpué",
  "Quillota","Quinta Normal","Quintero","Rancagua","Recoleta","Renca","Rengo",
  "Retiro","Río Bueno","Río Ibáñez","Río Negro","Sagrada Familia","Salamanca",
  "San Antonio","San Bernardo","San Carlos","San Clemente","San Esteban",
  "San Felipe","San Fernando","San Ignacio","San Javier","San Joaquín",
  "San José de Maipo","San Miguel","San Nicolás","San Pedro","San Pedro de Atacama",
  "San Pedro de la Paz","Santa Bárbara","Santa Cruz","Santa Juana","Santa María",
  "Santiago","Santo Domingo","Sierra Gorda","Talagante","Talca","Talcahuano",
  "Taltal","Temuco","Tierra Amarilla","Tiltil","Tocopilla","Tomé","Tortel",
  "Traiguén","Tucapel","Valdivia","Vallenar","Valparaíso","Victoria","Vicuña",
  "Villa Alemana","Villarrica","Viña del Mar","Vitacura","Yumbel","Zapallar",
].sort();

// ─── Región Metropolitana communes (used for RM vs. national pricing) ─────────
export const RM_COMUNAS = new Set([
  "Alhué","Buin","Calera de Tango","Cerrillos","Cerro Navia","Colina","Conchalí",
  "Curacaví","El Bosque","El Monte","Estación Central","Huechuraba","Independencia",
  "Isla de Maipo","La Cisterna","La Florida","La Granja","La Pintana","La Reina",
  "Lampa","Las Condes","Lo Barnechea","Lo Espejo","Lo Prado","Macul","Maipú",
  "María Pinto","Melipilla","Ñuñoa","Padre Hurtado","Paine","Pedro Aguirre Cerda",
  "Peñaflor","Peñalolén","Pirque","Providencia","Pudahuel","Puente Alto","Quilicura",
  "Quinta Normal","Recoleta","Renca","San Bernardo","San Joaquín","San José de Maipo",
  "San Miguel","San Pedro","Santiago","Talagante","Tiltil","Vitacura",
]);
